- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
    homebrew_packages:
      - { name: readline }
      - { name: libtool }
      - { name: zlib }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: ansible }
      - { name: coreutils }
      - { name: git }
      - { name: rbenv }
      - { name: zsh, install_options: disable-etcdir }
      - { name: zplug }
      - { name: peco }
      - { name: jq }
      - { name: wget }
      - { name: curl }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: pkg-config }
      - { name: tree }
      - { name: nkf }
      - { name: jq }
      - { name: go }
      - { name: tig }
      - { name: ruby-build }
      - { name: mysql }
      - { name: imagemagick }
      - { name: gibo }
      - { name: lua }
      - { name: vim, install_options: with-lua }
      - { name: mas }
    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: karabiner-elements }
      - { name: google-chrome }
      - { name: java }
      - { name: slack }
      - { name: alfred }
      - { name: vagrant }
      - { name: virtualbox }
    # appstore:
    #   - name: Evernote
    #     id: 406056744
    #   - name: The Unarchiver
    #     id: 425424353


  tasks:
    - name: Add homebrew tap repository
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: Update homebrew
      homebrew: update_homebrew=yes

    # brew
    - name: Install hombrew packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: Make directory to save brew package information
      file: path=brew_info state=directory
    - name: Save brew package information
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # brew cask
    - name: Install homebrew_cask_packages
      command: brew install Caskroom/cask/{{ item.name }}
      with_items: homebrew_cask_packages
